#!/usr/bin/env bash
# Installs nginx and starts it
sudo apt-get y update
apt -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
service nginx restart
