#!/usr/bin/env bash
# Installs nginx and starts it
sudo apt-get -y update
sudo apt -y install nginx
sudo service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo ervice nginx restart
