#!/usr/bin/env bash
# This script installs a nginx web server

sudo apt update
sudo apt install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status
systemctl status nginx
mkdir -p /var/www/html/
touch /var/www/html/index.html
echo 'Hello World!' | sudo tee /var/www/html/index.html
printf %s "server {
location /redirect_me {
        return 301 http://google.com/doodles/;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
