#!/usr/bin/env bash
# This script installs a nginx web server

sudo apt update
sudo apt install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status
systemctl status nginx
mkdir -p /var/www/html/
touch /var/www/html/index.html
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://twitter.com/Emmanue17280546;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
